import React,{useState} from 'react';
import { Row } from '../types';
import { money } from '../utils/format';

export default function PaymentModal({bill,onClose,onSubmit}:{bill:Row;onClose:()=>void;onSubmit:(body:any)=>Promise<void>}){
 const [amount,setAmount]=useState(String(bill.BalanceAmount??bill.Amount??0)); const [method,setMethod]=useState('BANK_TRANSFER'); const [date,setDate]=useState(new Date().toISOString().slice(0,10)); const [referenceNo,setReferenceNo]=useState(''); const [note,setNote]=useState(''); const [busy,setBusy]=useState(false);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await onSubmit({amount:Number(amount),paymentMethod:method,paymentDate:date,referenceNo,note});onClose()}finally{setBusy(false)}};
 return <div className="modal-mask"><div className="modal"><div className="modal-head"><div><h2>收款</h2><small>{bill.BillNo} · {bill.CustomerName}</small></div><button onClick={onClose}>×</button></div><form className="modal-form" onSubmit={submit}><div className="payment-summary"><span>帳單總額 <b>{money(bill.Amount)}</b></span><span>已收 <b>{money(bill.PaidAmount||0)}</b></span><span>未收 <b>{money(bill.BalanceAmount??bill.Amount)}</b></span></div><label>本次收款<input type="number" min="0.01" step="0.01" max={Number(bill.BalanceAmount??bill.Amount)} value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>付款方式<select value={method} onChange={e=>setMethod(e.target.value)}><option value="CASH">現金</option><option value="BANK_TRANSFER">銀行轉帳</option><option value="CREDIT_CARD">信用卡</option><option value="CHECK">支票</option><option value="OTHER">其他</option></select></label><label>付款日期<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>交易/匯款編號<input value={referenceNo} onChange={e=>setReferenceNo(e.target.value)}/></label><label className="full-field">備註<input value={note} onChange={e=>setNote(e.target.value)}/></label><div className="modal-actions"><button type="button" className="btn-secondary" onClick={onClose}>取消</button><button type="submit" disabled={busy}>{busy?'處理中...':'確認收款'}</button></div></form></div></div>
}
