import { useEffect, useMemo, useState } from 'react';
import { Row } from '../types';
import { money } from '../utils/format';

export default function ReturnModal({sale,onClose,onLoadDetail,onSubmit}:{sale:Row;onClose:()=>void;onLoadDetail:(id:number)=>Promise<any>;onSubmit:(body:any)=>Promise<void>}){
 const [data,setData]=useState<any>(null); const [qtys,setQtys]=useState<Record<number,number>>({}); const [reason,setReason]=useState(''); const [busy,setBusy]=useState(false); const [err,setErr]=useState('');
 useEffect(()=>{onLoadDetail(Number(sale.Id)).then(setData).catch(e=>setErr(e.message))},[sale.Id]);
 const total=useMemo(()=>!data?0:data.items.reduce((sum:number,x:Row)=>sum+(Number(qtys[x.Id]||0)*Number(x.UnitPrice||0)),0),[data,qtys]);
 const submit=async()=>{if(!data)return;const items=data.items.filter((x:Row)=>Number(qtys[x.Id]||0)>0).map((x:Row)=>({salesOrderDetailId:Number(x.Id),qty:Number(qtys[x.Id])}));if(!items.length){setErr('至少輸入一筆退貨數量');return;}setBusy(true);setErr('');try{await onSubmit({salesOrderId:Number(sale.Id),returnDate:new Date().toISOString().slice(0,10),reason,items});onClose();}catch(e:any){setErr(e.message||'退貨失敗')}finally{setBusy(false)}};
 return <div className="modal-mask"><div className="modal order-detail-modal"><div className="modal-head"><div><h2>建立退貨單</h2><small>{sale.OrderNo}｜{sale.CustomerName}</small></div><button onClick={onClose}>×</button></div>{!data?<div className="empty">讀取銷貨明細中...</div>:<><div className="order-detail-note"><span>退貨原因</span><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="例如：商品瑕疵、客戶取消" /></div><div className="order-lines-wrap modal-table"><table className="order-lines"><thead><tr><th>SKU</th><th>商品</th><th>原銷售量</th><th>已退</th><th>可退</th><th>單價</th><th>本次退貨量</th><th>退貨小計</th></tr></thead><tbody>{data.items.map((x:Row)=><tr key={x.Id}><td>{x.Sku}</td><td>{x.ProductName}</td><td>{x.Qty} {x.Unit}</td><td>{x.ReturnedQty||0}</td><td>{x.ReturnableQty??x.Qty}</td><td>{money(x.UnitPrice)}</td><td><input type="number" min="0" max={Number(x.ReturnableQty??x.Qty)} step="0.01" value={qtys[x.Id]??0} onChange={e=>setQtys(v=>({...v,[x.Id]:Number(e.target.value)}))}/></td><td>{money(Number(qtys[x.Id]||0)*Number(x.UnitPrice||0))}</td></tr>)}</tbody></table></div>{err&&<div className="form-error modal-table">{err}</div>}<div className="return-summary"><span>本次退貨總額</span><strong>{money(total)}</strong><button className="btn-secondary" onClick={onClose}>取消</button><button onClick={submit} disabled={busy}>{busy?'處理中...':'確認退貨'}</button></div></>}</div></div>
}
