import React,{useEffect,useState} from 'react'; import { api } from './api/client'; import { ActivityHistory, EditState, MasterKind, OrderCreatePayload, Row, ToastState } from './types'; import { labelMap } from './utils/format';
import Sidebar from './components/Sidebar'; import Toast from './components/Toast'; import ActivityBar from './components/ActivityBar'; import EditModal from './components/EditModal';
import DashboardPage from './pages/DashboardPage'; import InventoryCountPage from './pages/InventoryCountPage'; import ReportsPage from './pages/ReportsPage'; import ProductsPage from './pages/ProductsPage'; import PartyPage from './pages/PartyPage'; import OrderPage from './pages/OrderPage'; import ReturnsPage from './pages/ReturnsPage'; import SimpleTablePage from './pages/SimpleTablePage'; import HistoryPage from './pages/HistoryPage'; import BillingPage from './pages/BillingPage'; import InvoicesPage from './pages/InvoicesPage';

export default function App(){
 const [theme,setTheme]=useState<'light'|'dark'>(()=>{const saved=localStorage.getItem('lvb-flowstock-theme');if(saved==='light'||saved==='dark')return saved;return window.matchMedia?.('(prefers-color-scheme: dark)').matches?'dark':'light'});
 const [tab,setTab]=useState('dashboard'); const [counts,setCounts]=useState<Row[]>([]); const [products,setProducts]=useState<Row[]>([]); const [customers,setCustomers]=useState<Row[]>([]); const [suppliers,setSuppliers]=useState<Row[]>([]); const [sales,setSales]=useState<Row[]>([]); const [purchases,setPurchases]=useState<Row[]>([]); const [returns,setReturns]=useState<Row[]>([]); const [bills,setBills]=useState<Row[]>([]); const [invoices,setInvoices]=useState<Row[]>([]); const [adjustments,setAdjustments]=useState<Row[]>([]); const [txs,setTxs]=useState<Row[]>([]); const [history,setHistory]=useState<ActivityHistory[]>([]); const [toast,setToast]=useState<ToastState>(null); const [edit,setEdit]=useState<EditState>(null);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('lvb-flowstock-theme',theme)},[theme]);
 const showToast=(type:'success'|'error',text:string)=>{setToast({type,text});window.setTimeout(()=>setToast(null),3000)}; const mutationError=(e:any)=>showToast('error',e?.message||'操作失敗');
 const load=async()=>{try{const [p,c,s,sa,pu,re,b,iv,adj,t,h,ic]=await Promise.all([api('/products'),api('/customers'),api('/suppliers'),api('/sales'),api('/purchases'),api('/returns'),api('/billings'),api('/invoices'),api('/invoice-adjustments'),api('/inventory/transactions'),api('/history'),api('/inventory-counts')]);setProducts(p);setCustomers(c);setSuppliers(s);setSales(sa);setPurchases(pu);setReturns(re);setBills(b);setInvoices(iv);setAdjustments(adj);setTxs(t);setHistory(h);setCounts(ic);}catch(e:any){mutationError(e)}}; useEffect(()=>{load()},[]);
 const completed=async(message:string)=>{showToast('success',message);await load()};
 const addProduct=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;try{await api('/products',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();await completed('商品新增成功')}catch(err:any){mutationError(err)}};
 const addParty=(kind:'customers'|'suppliers')=>async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;try{await api(`/${kind}`,{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();await completed(`${labelMap[kind]}新增成功`)}catch(err:any){mutationError(err)}};
 const saveEdit=async(body:Record<string,any>)=>{if(!edit)return;try{await api(`/${edit.kind}/${edit.row.Id}`,{method:'PUT',body:JSON.stringify(body)});const label=labelMap[edit.kind];setEdit(null);await completed(`${label}修改成功`)}catch(err:any){mutationError(err)}};
 const removeRow=async(kind:MasterKind,row:Row)=>{const label=labelMap[kind];const name=row.Name||row.Sku||row.Code;if(!window.confirm(`確定要刪除${label}「${name}」嗎？`))return;try{await api(`/${kind}/${row.Id}`,{method:'DELETE'});await completed(`${label}刪除成功`)}catch(err:any){mutationError(err)}};
 const orderForm=(kind:'sales'|'purchases')=>async(body:OrderCreatePayload)=>{try{const result=await api(`/${kind}`,{method:'POST',body:JSON.stringify(body)});await completed(`${labelMap[kind]}新增成功，共 ${result.itemCount??body.items.length} 筆明細`)}catch(err:any){mutationError(err);throw err}};
 const addPayment=async(id:number,body:any)=>{try{const r=await api(`/billings/${id}/payments`,{method:'POST',body:JSON.stringify(body)});await completed(`收款成功，剩餘應收 ${Number(r.balanceAmount||0).toLocaleString('zh-TW')}`)}catch(e:any){mutationError(e);throw e}};
 const addRefund=async(id:number,body:any)=>{try{const r=await api(`/billings/${id}/refunds`,{method:'POST',body:JSON.stringify(body)});await completed(`退款登錄成功，剩餘待退款 ${Number(r.refundDue||0).toLocaleString('zh-TW')}`)}catch(e:any){mutationError(e);throw e}};
 const billingDetail=(id:number)=>api(`/billings/${id}`); const salesDetail=(id:number)=>api(`/sales/${id}`);
 const voidOrder=(kind:'sales'|'purchases')=>async(id:number)=>{try{const r=await api(`/${kind}/${id}/void`,{method:'POST'});await completed(r.message||'單據已作廢')}catch(e:any){mutationError(e)}};
 const createReturn=async(body:any)=>{try{const r=await api('/returns',{method:'POST',body:JSON.stringify(body)});await completed(`退貨完成：${r.returnNo}，共 ${r.itemCount} 筆明細`)}catch(e:any){mutationError(e);throw e}};
 const createInvoice=async(id:number,body:any)=>{try{await api(`/billings/${id}/invoices`,{method:'POST',body:JSON.stringify(body)});await completed('發票草稿建立成功')}catch(e:any){mutationError(e);throw e}};
 const issueInvoice=async(id:number)=>{try{const r=await api(`/invoices/${id}/issue`,{method:'POST'});await completed(r.message||'發票已標記開立')}catch(e:any){mutationError(e)}};
 const applyAdjustment=async(id:number)=>{try{const r=await api(`/invoice-adjustments/${id}/apply`,{method:'POST'});await completed(r.message||'發票調整已完成')}catch(e:any){mutationError(e)}};
 return <div className="app"><Sidebar tab={tab} onChange={setTab} theme={theme} onToggleTheme={()=>setTheme(t=>t==='light'?'dark':'light')}/><main>{toast&&<Toast type={toast.type} text={toast.text} onClose={()=>setToast(null)}/>} {tab==='dashboard'&&<DashboardPage products={products} sales={sales} bills={bills}/>} {tab==='products'&&<ProductsPage rows={products} onAdd={addProduct} onEdit={r=>setEdit({kind:'products',row:r})} onDelete={r=>removeRow('products',r)}/>} {tab==='customers'&&<PartyPage title="客戶" rows={customers} submit={addParty('customers')} onEdit={r=>setEdit({kind:'customers',row:r})} onDelete={r=>removeRow('customers',r)}/>} {tab==='suppliers'&&<PartyPage title="供應商" rows={suppliers} submit={addParty('suppliers')} onEdit={r=>setEdit({kind:'suppliers',row:r})} onDelete={r=>removeRow('suppliers',r)}/>} {tab==='purchases'&&<OrderPage kind="purchases" parties={suppliers} products={products} orders={purchases} submit={orderForm('purchases')} onError={m=>showToast('error',m)} onVoid={voidOrder('purchases')}/>}  {tab==='sales'&&<OrderPage kind="sales" parties={customers} products={products} orders={sales} submit={orderForm('sales')} onError={m=>showToast('error',m)} onVoid={voidOrder('sales')}/>}  {tab==='returns'&&<ReturnsPage sales={sales} returns={returns} onLoadSale={salesDetail} onCreateReturn={createReturn}/>} {tab==='counts'&&<InventoryCountPage products={products} rows={counts} onDone={completed} onError={m=>showToast('error',m)}/>} {tab==='inventory'&&<SimpleTablePage title="庫存異動" rows={txs} cols={['CreatedAt','Sku','ProductName','TxType','Qty','BeforeQty','AfterQty','ReferenceType','ReferenceId']}/>} {tab==='billing'&&<BillingPage rows={bills} onPayment={addPayment} onRefund={addRefund} onDetail={billingDetail} onInvoice={createInvoice}/>} {tab==='invoices'&&<InvoicesPage rows={invoices} adjustments={adjustments} onIssue={issueInvoice} onApplyAdjustment={applyAdjustment}/>} {tab==='reports'&&<ReportsPage/>} {tab==='history'&&<HistoryPage rows={history}/>}</main><ActivityBar latest={history[0]} onOpenHistory={()=>setTab('history')}/>{edit&&<EditModal edit={edit} onCancel={()=>setEdit(null)} onSave={saveEdit}/>}</div>;
}
